# Generated by Django 4.2.3 on 2023-08-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fac_tipos_movimientos',
            fields=[
                ('cod_movimiento', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código Movimiento')),
                ('nbr_movimiento', models.CharField(max_length=50, verbose_name='Nombre Movimiento')),
                ('lsv_efecto', models.CharField(max_length=1, verbose_name='Efecto del Movimiento')),
                ('str_serie_doc', models.CharField(max_length=12, verbose_name='Serie del Documento')),
                ('num_correlativo_actual', models.BigIntegerField()),
            ],
            options={
                'db_table': 'fac_tipos_movimientos',
            },
        ),
    ]
