# Generated by Django 4.2.3 on 2023-08-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adm_contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Contacto')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('tipo_consulta', models.IntegerField(choices=[(1, 'Consulta'), (2, 'Reclamo'), (3, 'Sugerencia'), (4, 'Comentario')], default=1, verbose_name='Tipo Consulta')),
                ('mensaje', models.TextField()),
                ('avisos', models.BooleanField()),
            ],
            options={
                'db_table': 'adm_contactos',
            },
        ),
    ]
