# Generated by Django 4.2.3 on 2023-08-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adm_contactos',
            name='tipo_consulta',
            field=models.IntegerField(choices=[(0, 'Consulta'), (1, 'Reclamo'), (2, 'Sugerencia'), (3, 'Comentario')], default=1, verbose_name='Tipo Consulta'),
        ),
    ]
