# Generated by Django 4.2.3 on 2023-08-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_adm_contactos_tipo_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adm_contactos',
            name='avisos',
            field=models.BooleanField(verbose_name='Recibir Avisos'),
        ),
        migrations.AlterField(
            model_name='adm_contactos',
            name='mensaje',
            field=models.CharField(max_length=254, verbose_name='Mensaje a Enviar'),
        ),
    ]
