# Generated by Django 4.2.3 on 2023-08-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_adm_contactos_avisos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adm_contactos',
            name='mensaje',
            field=models.TextField(verbose_name='Mensaje Enviado'),
        ),
    ]
