# Generated by Django 4.2.3 on 2023-08-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_alter_adm_contactos_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adm_contactos',
            name='mensaje',
            field=models.CharField(max_length=254, verbose_name='Mensaje Enviado'),
        ),
    ]
