# Generated by Django 4.2.3 on 2023-08-04 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inv_cajas',
            fields=[
                ('cod_caja', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código Caja')),
                ('nbr_caja', models.CharField(max_length=50, verbose_name='Nombre Caja')),
            ],
            options={
                'db_table': 'inv_cajas',
            },
        ),
        migrations.CreateModel(
            name='inv_lineas_productos',
            fields=[
                ('cod_linea', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código Línea')),
                ('nbr_linea', models.CharField(max_length=50, verbose_name='Nombre Línea')),
            ],
            options={
                'db_table': 'inv_lineas_productos',
            },
        ),
        migrations.CreateModel(
            name='inv_tipos_movimientos',
            fields=[
                ('cod_tipo_mov', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código Tipo Movimiento')),
                ('nbr_tipo_mov', models.CharField(max_length=50, verbose_name='Nombre Tipo Movimiento')),
                ('lsv_efecto', models.CharField(max_length=1, verbose_name='Efecto del Movimiento')),
            ],
            options={
                'db_table': 'inv_tipos_movimientos',
            },
        ),
        migrations.CreateModel(
            name='inv_unidades_medida',
            fields=[
                ('cod_unidad', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código Unidad')),
                ('nbr_unidad', models.CharField(max_length=30, verbose_name='Nombre Unidad')),
            ],
            options={
                'db_table': 'inv_unidades_medida',
            },
        ),
        migrations.CreateModel(
            name='inv_catalogo_productos',
            fields=[
                ('cod_producto', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código Producto')),
                ('nbr_producto', models.CharField(max_length=60, verbose_name='Nombre Producto')),
                ('cod_barra', models.CharField(max_length=30, verbose_name='Código de Barra')),
                ('val_costo_unitario', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Costo Unitario')),
                ('val_precio_venta', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Precio de Venta')),
                ('num_existencia_actual', models.IntegerField(verbose_name='Existencia Actual')),
                ('cod_linea', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventarios.inv_lineas_productos')),
                ('cod_unidad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventarios.inv_unidades_medida')),
            ],
            options={
                'db_table': 'inv_catalogo_productos',
            },
        ),
    ]
